apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: metrics
  project: default
  source:
    chart: charts/grafana
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 5.2.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
